services:
  frontend:
    image: bindushreegd/my-fullstack-app-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: bindushreegd/my-fullstack-app-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: