version: "3.8"

services:
  backend:
    build:
      context: https://github.com/BindushreeGD/my-fullstack-app.git#main:backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: https://github.com/BindushreeGD/my-fullstack-app.git#main:frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
