services:
  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my-database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
